#pragma once
#include <windows.h>
#include <gl/GL.h>
#include <gl/GLU.h>
//#include <GL\freeglut.h>
#include <SDL.h>
#include <SDL_ttf.h>
#include <glm\glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtx/transform.hpp>
#include "Object.h"
#include "Instance.h"
#include "GridMap.h"
#include "Camera.h"
#include "Loader.h"
#include "Render.h"
